# Generated by Django 3.0.6 on 2020-05-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_auto_20200524_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonatm',
            name='namedetails',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
