# Generated by Django 3.0.6 on 2020-05-24 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_anonatm_namedetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anonatm',
            old_name='extratags',
            new_name='extra_tags',
        ),
    ]
