# Generated by Django 3.0.6 on 2020-05-25 08:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_auto_20200524_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonatm',
            name='help_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='anonatm',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, default=list, size=None),
        ),
    ]
