# Generated by Django 3.0.6 on 2020-05-15 13:41

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_description', models.TextField()),
                ('bank_founded', models.DateField(blank=True, default=None, help_text='YYYY-MM-DD', null=True)),
                ('bank_type', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=100)),
                ('bank_class', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10)),
                ('bank_central_hq_address', models.CharField(blank=True, help_text='Read Only field', max_length=255, null=True)),
                ('bank_district_name', models.CharField(max_length=100)),
                ('bank_city_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_postal_code', models.IntegerField(blank=True, null=True)),
                ('bank_street_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_building_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_contact_number', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10, unique=True), size=None)),
                ('bank_website_url', models.URLField(blank=True, default=None, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, size=None)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'db_table': 'bank',
            },
        ),
        migrations.CreateModel(
            name='Subsidiary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subsidiary_name', models.CharField(max_length=255)),
                ('subsidiary_address', models.CharField(help_text='Read Only field', max_length=255)),
                ('subsidiary_district_name', models.CharField(max_length=100)),
                ('subsidiary_city_name', models.CharField(blank=True, max_length=100, null=True)),
                ('subsidiary_postal_code', models.IntegerField(blank=True, null=True)),
                ('subsidiary_street_name', models.CharField(blank=True, max_length=100, null=True)),
                ('subsidiary_building_number', models.CharField(blank=True, max_length=100, null=True)),
                ('subsidiary_contact_number', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10, unique=True), size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, size=None)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Bank')),
            ],
            options={
                'verbose_name': 'Subsidiary',
                'verbose_name_plural': 'Subsidiaries',
                'db_table': 'subsidiary',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=255)),
                ('branch_address', models.CharField(help_text='Read Only field', max_length=255)),
                ('branch_district_name', models.CharField(max_length=100)),
                ('branch_city_name', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_postal_code', models.IntegerField(blank=True, null=True)),
                ('branch_street_name', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_building_number', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_contact_number', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
                ('branch_atm_address', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, size=None)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Bank')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'db_table': 'branch',
            },
        ),
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('atm_address', models.CharField(help_text='Read Only field', max_length=100)),
                ('atm_district_name', models.CharField(max_length=100)),
                ('atm_city_name', models.CharField(blank=True, max_length=100, null=True)),
                ('atm_postal_code', models.IntegerField(blank=True, null=True)),
                ('atm_street_name', models.CharField(blank=True, max_length=100, null=True)),
                ('atm_building_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Bank')),
                ('branch', smart_selects.db_fields.ChainedManyToManyField(chained_field='bank', chained_model_field='branch_name', to='bank.Branch')),
            ],
            options={
                'verbose_name': 'ATM',
                'verbose_name_plural': "ATM's",
                'db_table': 'atm',
            },
        ),
    ]
