# Generated by Django 3.0.6 on 2020-05-16 05:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('atm_address', models.CharField(help_text='Read Only field', max_length=100)),
                ('atm_district_name', models.CharField(max_length=100)),
                ('atm_city_name', models.CharField(blank=True, max_length=100, null=True)),
                ('atm_postal_code', models.IntegerField(blank=True, null=True)),
                ('atm_street_name', models.CharField(blank=True, max_length=100, null=True)),
                ('atm_building_number', models.CharField(blank=True, max_length=100, null=True)),
                ('atm_help_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ATM',
                'verbose_name_plural': "ATM's",
                'db_table': 'atm',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_description', models.TextField()),
                ('bank_founded', models.DateField(blank=True, default=None, help_text='YYYY-MM-DD', null=True)),
                ('bank_type', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=100)),
                ('bank_class', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10)),
                ('bank_central_hq_address', models.CharField(blank=True, help_text='Read Only field', max_length=255, null=True)),
                ('bank_district_name', models.CharField(max_length=100)),
                ('bank_city_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_postal_code', models.IntegerField(blank=True, null=True)),
                ('bank_street_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_building_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_contact_number', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10, unique=True), size=None)),
                ('bank_website_url', models.URLField(blank=True, default=None, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, size=None)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'db_table': 'bank',
            },
        ),
        migrations.CreateModel(
            name='AnonATM',
            fields=[
                ('atm_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bank.ATM')),
            ],
            options={
                'verbose_name': 'Annon ATM',
                'verbose_name_plural': "Annon ATM's",
                'db_table': 'annon_atm',
            },
            bases=('bank.atm',),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=255)),
                ('branch_address', models.CharField(help_text='Read Only field', max_length=255)),
                ('branch_district_name', models.CharField(max_length=100)),
                ('branch_city_name', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_postal_code', models.IntegerField(blank=True, null=True)),
                ('branch_street_name', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_building_number', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_contact_number', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, size=None)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Bank')),
                ('branch_atm', models.ManyToManyField(blank=True, to='bank.ATM')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'db_table': 'branch',
            },
        ),
        migrations.AddField(
            model_name='atm',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Bank'),
        ),
    ]
