# Generated by Django 3.0.6 on 2020-05-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atm',
            name='atm_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
