# Generated by Django 3.0.6 on 2020-05-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonatm',
            name='atm_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='atm',
            name='atm_status',
            field=models.BooleanField(default=True),
        ),
    ]
