# Generated by Django 3.0.6 on 2020-05-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20200515_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='atm',
            name='atm_help_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Subsidiary',
        ),
    ]
