# Generated by Django 3.0.6 on 2020-05-16 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_atm_atm_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atm',
            name='atm_name',
        ),
    ]
