# Generated by Django 3.0.6 on 2020-05-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_remove_atm_atm_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bank_help_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_help_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
