# Generated by Django 3.0.6 on 2020-05-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20200516_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='atm',
            name='branch_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
