# Generated by Django 3.0.6 on 2020-05-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_atm_branch_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atm',
            name='branch_description',
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
