# Generated by Django 3.0.6 on 2020-05-16 08:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_auto_20200516_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='atm',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, default=None, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='branch_atm',
            field=models.ManyToManyField(blank=True, to='bank.ATM', verbose_name='branch atm(s)'),
        ),
    ]
