# Generated by Django 3.0.6 on 2020-05-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_auto_20200521_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='building_number',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='city_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='district_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='extra_tags',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='municipality',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='namedetails',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='neighbourhood',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='place_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='province',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='street_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
