# Generated by Django 3.0.6 on 2020-05-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_auto_20200524_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonatm',
            name='postal_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
